name: easy_date_time_example
description: Examples for easy_date_time package
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  dio: ^5.9.0
  easy_date_time:
    path: ../
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  retrofit: ^4.9.1

dev_dependencies:
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.9.5
  retrofit_generator: ^10.2.0
