name: easy_date_time_example
description: Examples for easy_date_time package
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.4.0
  easy_date_time:
    path: ../
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  retrofit: ^4.0.3

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  lints: ^3.0.0
  retrofit_generator: ^7.0.8
