name: easy_date_time
description: A drop-in DateTime alternative with full IANA timezone support.
version: 0.2.0
homepage: https://github.com/MasterHiei/easy_date_time
repository: https://github.com/MasterHiei/easy_date_time
issue_tracker: https://github.com/MasterHiei/easy_date_time/issues
documentation: https://github.com/MasterHiei/easy_date_time/blob/main/README.md

topics:
  - datetime
  - timezone
  - time
  - date
  - json

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  timezone: ">=0.9.4 <0.11.0"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
